/**
 * Tests for Kilo Code support (inject-only).
 *
 * Kilo Code (kilocode.ai, a VS Code extension forked from Roo/Cline) has no
 * shell-command hook system, so cc-habits cannot capture edits from it. What it
 * can do is inject: Kilo reads AGENTS.md natively, and cc-habits also writes a
 * dedicated rules file cc-habits owns outright.
 *
 * Covers:
 *   - syncTargets(['kilo']): writes .kilo/rules/cch.md and .kilocode/rules/cch.md
 *     with the expected header and habit content
 *   - fail-open: a write failure on one of the two rules paths does not throw
 *     and does not block the other path
 *   - isKiloCodeInstalled(): true/false detection via a mocked VS Code
 *     extensions directory
 *   - supported.ts: Kilo Code is listed as inject-only, with no hook adapter
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { syncTargets, readSyncTargets } from '../src/sync';
import { parseHabits, storagePaths } from '../src/storage';
import { isKiloCodeInstalled } from '../src/detect';
import { SUPPORTED_TOOLS, HOOK_ADAPTERS } from '../src/supported';

const origStorage = { ...storagePaths };
let tmpDir: string;

const SEEDED = `<!-- cc-habits format v0.2 -->
# Coding habits

Auto-generated by cc-habits.

## TypeScript

- Use explicit return types on exported functions. Confidence: 0.80
  - Signal: 5 reinforcing, 0 contradicting
  - Sessions seen: 3
`;

function seed(content: string): void {
  fs.writeFileSync(storagePaths.habitsFile, content);
}

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-habits-kilo-'));
  storagePaths.habitsFile = path.join(tmpDir, 'habits.md');
  seed(SEEDED);
});

afterEach(() => {
  Object.assign(storagePaths, origStorage);
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

describe('syncTargets: kilo', () => {
  it('writes both .kilo/rules/cch.md and .kilocode/rules/cch.md with the generated content', () => {
    const proj = path.join(tmpDir, 'proj');
    fs.mkdirSync(proj, { recursive: true });

    const result = syncTargets(['kilo'], { baseDir: proj });
    expect(result.skipped).toBe(false);

    const primary = fs.readFileSync(path.join(proj, '.kilo', 'rules', 'cch.md'), 'utf-8');
    const legacy = fs.readFileSync(path.join(proj, '.kilocode', 'rules', 'cch.md'), 'utf-8');

    for (const content of [primary, legacy]) {
      expect(content).toContain('Generated by cc-habits');
      expect(content).toContain('Safe to delete');
      expect(content).toContain('# Coding preferences');
      expect(content).toContain('Use explicit return types on exported functions.');
    }
    expect(result.written).toContain(path.join(proj, '.kilo', 'rules', 'cch.md'));
    expect(result.written).toContain(path.join(proj, '.kilocode', 'rules', 'cch.md'));
  });

  it('creates the .kilo/rules and .kilocode/rules directories when absent', () => {
    const proj = path.join(tmpDir, 'proj-fresh');
    fs.mkdirSync(proj, { recursive: true });
    expect(fs.existsSync(path.join(proj, '.kilo'))).toBe(false);
    expect(fs.existsSync(path.join(proj, '.kilocode'))).toBe(false);

    syncTargets(['kilo'], { baseDir: proj });

    expect(fs.statSync(path.join(proj, '.kilo', 'rules')).isDirectory()).toBe(true);
    expect(fs.statSync(path.join(proj, '.kilocode', 'rules')).isDirectory()).toBe(true);
  });

  it('overwrites the file wholesale on a second sync (no merge markers)', () => {
    const proj = path.join(tmpDir, 'proj-overwrite');
    fs.mkdirSync(proj, { recursive: true });
    fs.mkdirSync(path.join(proj, '.kilocode', 'rules'), { recursive: true });
    fs.writeFileSync(path.join(proj, '.kilocode', 'rules', 'cch.md'), 'stale content from a previous version\n');

    syncTargets(['kilo'], { baseDir: proj });

    const content = fs.readFileSync(path.join(proj, '.kilocode', 'rules', 'cch.md'), 'utf-8');
    expect(content).not.toContain('stale content');
    expect(content).toContain('Use explicit return types on exported functions.');
  });

  it('skips writing when there are no active habits', () => {
    seed(`<!-- cc-habits format v0.2 -->\n# Coding habits\n`);
    const proj = path.join(tmpDir, 'proj-empty');
    fs.mkdirSync(proj, { recursive: true });

    const result = syncTargets(['kilo'], { baseDir: proj });
    expect(result.skipped).toBe(true);
    expect(result.written).toHaveLength(0);
    expect(fs.existsSync(path.join(proj, '.kilo'))).toBe(false);
    expect(fs.existsSync(path.join(proj, '.kilocode'))).toBe(false);
  });

  it('is fail-open: a write failure on one rules path does not throw and does not block the other', () => {
    const proj = path.join(tmpDir, 'proj-blocked');
    fs.mkdirSync(proj, { recursive: true });
    // Put a plain file where the .kilo directory needs to go, so mkdirSync for
    // .kilo/rules fails with ENOTDIR. This mirrors "directory creation fails"
    // without relying on platform-specific permission bits (which root ignores
    // in CI), so it stays deterministic everywhere.
    fs.writeFileSync(path.join(proj, '.kilo'), 'not a directory');

    let result: ReturnType<typeof syncTargets> | undefined;
    expect(() => { result = syncTargets(['kilo'], { baseDir: proj }); }).not.toThrow();

    expect(result!.skipped).toBe(false);
    // The blocked path never got written...
    expect(result!.written).not.toContain(path.join(proj, '.kilo', 'rules', 'cch.md'));
    // ...but the backward-compatible path still succeeded.
    const legacy = fs.readFileSync(path.join(proj, '.kilocode', 'rules', 'cch.md'), 'utf-8');
    expect(legacy).toContain('Use explicit return types on exported functions.');
    expect(result!.written).toContain(path.join(proj, '.kilocode', 'rules', 'cch.md'));
  });

  it('readSyncTargets accepts kilo as a configured target', () => {
    storagePaths.configFile = path.join(tmpDir, 'config.yml');
    fs.writeFileSync(storagePaths.configFile, 'sync_targets: agents, kilo\n');
    expect(readSyncTargets()).toEqual(['agents', 'kilo']);
  });
});

describe('isKiloCodeInstalled', () => {
  let tmpHome: string;
  let homedirSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    tmpHome = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-habits-kilo-home-'));
    homedirSpy = vi.spyOn(os, 'homedir').mockReturnValue(tmpHome);
  });

  afterEach(() => {
    vi.restoreAllMocks();
    fs.rmSync(tmpHome, { recursive: true, force: true });
  });

  it('returns true when the extension folder is present under ~/.vscode/extensions', () => {
    fs.mkdirSync(path.join(tmpHome, '.vscode', 'extensions', 'kilocode.kilo-code-4.68.0'), { recursive: true });
    expect(isKiloCodeInstalled()).toBe(true);
  });

  it('returns true for a matching folder under ~/.vscode-insiders/extensions', () => {
    fs.mkdirSync(path.join(tmpHome, '.vscode-insiders', 'extensions', 'kilocode.kilo-code-4.70.1'), { recursive: true });
    expect(isKiloCodeInstalled()).toBe(true);
  });

  it('returns false when the extensions directory has no Kilo folder', () => {
    fs.mkdirSync(path.join(tmpHome, '.vscode', 'extensions', 'some-other.extension-1.0.0'), { recursive: true });
    expect(isKiloCodeInstalled()).toBe(false);
  });

  it('returns false when no VS Code extensions directory exists at all', () => {
    expect(isKiloCodeInstalled()).toBe(false);
  });

  it('is fail-open: never throws even if homedir resolution fails', () => {
    homedirSpy.mockImplementation(() => {
      throw new Error('no home');
    });
    expect(() => isKiloCodeInstalled()).not.toThrow();
    expect(isKiloCodeInstalled()).toBe(false);
  });
});

describe('supported.ts: Kilo Code listed inject-only', () => {
  it('lists kilo with an honest, non-empty capture and inject description', () => {
    const kilo = SUPPORTED_TOOLS.find(t => t.id === 'kilo');
    expect(kilo).toBeDefined();
    expect(kilo!.name).toContain('Kilo');
    // Honest: capture must not claim hooks exist for Kilo.
    expect(kilo!.capture.toLowerCase()).not.toContain('hooks (');
    expect(kilo!.inject.length).toBeGreaterThan(0);
  });

  it('does not add kilo to HOOK_ADAPTERS (no adapter exists for it)', () => {
    expect(HOOK_ADAPTERS).not.toContain('kilo');
  });
});
