/**
 * Tests for cc-habits sync, emitting learned habits into tool-agnostic preference
 * files (AGENTS.md, Cursor .mdc, Cline) so any coding agent can read them.
 *
 * Covers:
 *   - renderPortableBody: active-only, learning excluded, categories sorted
 *   - renderBlockOrNull: null when nothing is active
 *   - mergeBlock: insert, idempotent replace, preserves surrounding user content
 *   - syncTargets: writes each target, Cursor frontmatter, skip when empty
 *   - symlink refusal
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  renderPortableBody, renderBlockOrNull, mergeBlock, syncTargets,
  readSyncTargets, writePreferencesFile, BEGIN_MARKER, END_MARKER,
} from '../src/sync';
import { parseHabits, storagePaths } from '../src/storage';

const origStorage = { ...storagePaths };
let tmpDir: string;

const SEEDED = `<!-- cc-habits format v0.2 -->
# Coding habits

Auto-generated by cc-habits.

## TypeScript

- Use explicit return types on exported functions. Confidence: 0.80
  - Signal: 5 reinforcing, 0 contradicting
  - Sessions seen: 3

## Naming

- Use camelCase for variables. Confidence: 0.90
  - Signal: 8 reinforcing, 0 contradicting
  - Sessions seen: 4

## Learning (not yet active)

- [Imports] Prefer named imports over default. Confidence: 0.50
  - Signal: 1 reinforcing, 0 contradicting
  - Sessions seen: 1
`;

function seed(content: string): void {
  fs.writeFileSync(storagePaths.habitsFile, content);
}

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-habits-sync-'));
  storagePaths.habitsFile = path.join(tmpDir, 'habits.md');
  seed(SEEDED);
});

afterEach(() => {
  Object.assign(storagePaths, origStorage);
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

describe('renderPortableBody', () => {
  it('includes active habits, sorted by category, excludes the learning section', () => {
    const body = renderPortableBody(parseHabits(SEEDED));
    expect(body).toContain('## Naming');
    expect(body).toContain('## TypeScript');
    expect(body).toContain('- Use camelCase for variables.');
    // sorted: Naming before TypeScript
    expect(body.indexOf('## Naming')).toBeLessThan(body.indexOf('## TypeScript'));
    // learning-section rule must NOT leak
    expect(body).not.toContain('Prefer named imports');
    // no confidence math / signal counts in the portable form
    expect(body).not.toContain('Confidence:');
    expect(body).not.toContain('Sessions seen');
  });

  it('respects the minConfidence filter', () => {
    const body = renderPortableBody(parseHabits(SEEDED), 0.85);
    expect(body).toContain('Use camelCase'); // 0.90 passes
    expect(body).not.toContain('explicit return types'); // 0.80 filtered out
  });
});

describe('renderBlockOrNull', () => {
  it('returns a body when active habits exist', () => {
    expect(renderBlockOrNull()).toContain('# Coding preferences');
  });

  it('returns null when there are no active habits', () => {
    seed(`<!-- cc-habits format v0.2 -->
# Coding habits

## Learning (not yet active)

- [Imports] Prefer named imports. Confidence: 0.50
  - Sessions seen: 1
`);
    expect(renderBlockOrNull()).toBeNull();
  });
});

describe('mergeBlock', () => {
  it('appends a block when none exists, preserving existing content', () => {
    const out = mergeBlock('# My Project\n\nNotes.\n', 'BODY');
    expect(out).toContain('# My Project');
    expect(out).toContain('Notes.');
    expect(out).toContain(BEGIN_MARKER);
    expect(out).toContain('BODY');
    expect(out).toContain(END_MARKER);
  });

  it('replaces an existing block idempotently (single marker pair)', () => {
    const first = mergeBlock('# Doc\n', 'BODY-1');
    const second = mergeBlock(first, 'BODY-2');
    expect((second.match(new RegExp(BEGIN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) ?? []).length).toBe(1);
    expect(second).toContain('BODY-2');
    expect(second).not.toContain('BODY-1');
    expect(second).toContain('# Doc');
  });

  it('handles empty input', () => {
    const out = mergeBlock('', 'BODY');
    expect(out).toContain(BEGIN_MARKER);
    expect(out).toContain('BODY');
  });
});

describe('syncTargets', () => {
  it('writes AGENTS.md and merges with existing content', () => {
    const proj = path.join(tmpDir, 'proj');
    fs.mkdirSync(proj, { recursive: true });
    fs.writeFileSync(path.join(proj, 'AGENTS.md'), '# Project\n\nKeep me.\n');

    const result = syncTargets(['agents'], { baseDir: proj });
    expect(result.skipped).toBe(false);
    const content = fs.readFileSync(path.join(proj, 'AGENTS.md'), 'utf-8');
    expect(content).toContain('Keep me.');
    expect(content).toContain('# Coding preferences');
    expect(content).toContain('Use camelCase');
  });

  it('writes a Cursor .mdc with alwaysApply frontmatter', () => {
    const proj = path.join(tmpDir, 'proj-cursor');
    fs.mkdirSync(proj, { recursive: true });
    syncTargets(['cursor'], { baseDir: proj });
    const mdc = fs.readFileSync(path.join(proj, '.cursor', 'rules', 'cc-habits.mdc'), 'utf-8');
    expect(mdc).toMatch(/^---\n/);
    expect(mdc).toContain('alwaysApply: true');
    expect(mdc).toContain('Use camelCase');
  });

  it('writes .clinerules as a file when no directory exists', () => {
    const proj = path.join(tmpDir, 'proj-cline');
    fs.mkdirSync(proj, { recursive: true });
    syncTargets(['cline'], { baseDir: proj });
    expect(fs.existsSync(path.join(proj, '.clinerules'))).toBe(true);
    expect(fs.statSync(path.join(proj, '.clinerules')).isFile()).toBe(true);
  });

  it('writes inside .clinerules/ when it is a directory', () => {
    const proj = path.join(tmpDir, 'proj-clinedir');
    fs.mkdirSync(path.join(proj, '.clinerules'), { recursive: true });
    syncTargets(['cline'], { baseDir: proj });
    expect(fs.existsSync(path.join(proj, '.clinerules', 'cc-habits.md'))).toBe(true);
  });

  it('skips writing when there are no active habits', () => {
    seed(`<!-- cc-habits format v0.2 -->\n# Coding habits\n`);
    const proj = path.join(tmpDir, 'proj-empty');
    fs.mkdirSync(proj, { recursive: true });
    const result = syncTargets(['agents'], { baseDir: proj });
    expect(result.skipped).toBe(true);
    expect(result.written).toHaveLength(0);
    expect(fs.existsSync(path.join(proj, 'AGENTS.md'))).toBe(false);
  });

  it.skipIf(process.platform === 'win32')('refuses to write through a symlink', () => {
    const proj = path.join(tmpDir, 'proj-symlink');
    fs.mkdirSync(proj, { recursive: true });
    const target = path.join(tmpDir, 'real-target.md');
    fs.writeFileSync(target, 'secret');
    fs.symlinkSync(target, path.join(proj, 'AGENTS.md'));
    expect(() => syncTargets(['agents'], { baseDir: proj })).toThrow(/symlink/);
  });
});

describe('readSyncTargets', () => {
  beforeEach(() => {
    storagePaths.configFile = path.join(tmpDir, 'config.yml');
  });

  it('returns empty array when config file does not exist', () => {
    expect(readSyncTargets()).toEqual([]);
  });

  it('parses sync_targets from simple format', () => {
    fs.writeFileSync(storagePaths.configFile, 'provider: ollama\nsync_targets: cursor, cline\n');
    expect(readSyncTargets()).toEqual(['cursor', 'cline']);
  });

  it('parses sync_targets from bracketed format', () => {
    fs.writeFileSync(storagePaths.configFile, 'provider: openai\nsync_targets: [agents, cursor]\n');
    expect(readSyncTargets()).toEqual(['agents', 'cursor']);
  });

  it('filters out invalid sync targets', () => {
    fs.writeFileSync(storagePaths.configFile, 'sync_targets: cursor, invalid, cline\n');
    expect(readSyncTargets()).toEqual(['cursor', 'cline']);
  });
});

describe('writePreferencesFile', () => {
  // Re-point storagePaths so writePreferencesFile writes into tmpDir.
  beforeEach(() => {
    storagePaths.preferencesFile = path.join(tmpDir, 'preferences.md');
  });

  it('writes a clean markdown body with no confidence metadata for active habits', () => {
    // SEEDED has two active habits (sessions_seen >= 2) and one learning habit.
    writePreferencesFile();
    const content = fs.readFileSync(storagePaths.preferencesFile, 'utf-8');
    // Clean body: human-readable rules only.
    expect(content).toContain('## Naming');
    expect(content).toContain('- Use camelCase for variables.');
    expect(content).toContain('## TypeScript');
    expect(content).toContain('- Use explicit return types on exported functions.');
    // No internal metadata.
    expect(content).not.toContain('Confidence:');
    expect(content).not.toContain('Sessions seen');
    expect(content).not.toContain('reinforcing');
    // Learning-section rule must not leak.
    expect(content).not.toContain('Prefer named imports');
  });

  it('writes a placeholder notice when no habits have graduated', () => {
    seed(`<!-- cc-habits format v0.2 -->
# Coding habits

## Learning (not yet active)

- [Imports] Prefer named imports. Confidence: 0.50
  - Sessions seen: 1
`);
    writePreferencesFile();
    const content = fs.readFileSync(storagePaths.preferencesFile, 'utf-8');
    expect(content).toContain('No preferences have graduated yet');
    // Still no metadata exposed.
    expect(content).not.toContain('Confidence:');
  });

  it('overwrites the file on a second call (idempotent)', () => {
    writePreferencesFile();
    const first = fs.readFileSync(storagePaths.preferencesFile, 'utf-8');
    writePreferencesFile();
    const second = fs.readFileSync(storagePaths.preferencesFile, 'utf-8');
    expect(first).toBe(second);
    // Exactly one copy of the heading.
    expect((second.match(/# Coding preferences/g) ?? []).length).toBe(1);
  });

  it('passing an in-memory cats map yields a byte-identical file to the disk path', () => {
    // Perf optimisation: processStop passes the already-parsed map to skip a
    // read-back + re-parse. This guards the invariant that the cats path produces
    // exactly the same preferences.md as reading and parsing habits.md from disk.
    writePreferencesFile();
    const fromDisk = fs.readFileSync(storagePaths.preferencesFile, 'utf-8');
    fs.rmSync(storagePaths.preferencesFile);
    const cats = parseHabits(fs.readFileSync(storagePaths.habitsFile, 'utf-8'));
    writePreferencesFile(undefined, cats);
    const fromCats = fs.readFileSync(storagePaths.preferencesFile, 'utf-8');
    expect(fromCats).toBe(fromDisk);
  });

  it('passing an empty cats map emits the no-graduated-habits placeholder', () => {
    writePreferencesFile(undefined, {});
    const content = fs.readFileSync(storagePaths.preferencesFile, 'utf-8');
    expect(content).toContain('No preferences have graduated yet');
  });

  it.skipIf(process.platform === 'win32')('refuses to write through a symlink', () => {
    const target = path.join(tmpDir, 'real-prefs.md');
    fs.writeFileSync(target, 'secret');
    fs.symlinkSync(target, storagePaths.preferencesFile);
    expect(() => writePreferencesFile()).toThrow(/symlink/);
    // Original target must not be overwritten.
    expect(fs.readFileSync(target, 'utf-8')).toBe('secret');
  });
});
