/**
 * Tests for cc-habits sync — emitting learned habits into tool-agnostic preference
 * files (AGENTS.md, Cursor .mdc, Cline) so any coding agent can read them.
 *
 * Covers:
 *   - renderPortableBody: active-only, learning excluded, categories sorted
 *   - renderBlockOrNull: null when nothing is active
 *   - mergeBlock: insert, idempotent replace, preserves surrounding user content
 *   - syncTargets: writes each target, Cursor frontmatter, skip when empty
 *   - symlink refusal
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { storagePaths } from '../src/storage';
import {
  renderPortableBody, renderBlockOrNull, mergeBlock, syncTargets,
  BEGIN_MARKER, END_MARKER,
} from '../src/sync';
import { parseHabits } from '../src/storage';

const origStorage = { ...storagePaths };
let tmpDir: string;

const SEEDED = `<!-- cc-habits format v0.2 -->
# Coding habits

Auto-generated by cc-habits.

## TypeScript

- Use explicit return types on exported functions. Confidence: 0.80
  - Signal: 5 reinforcing, 0 contradicting
  - Sessions seen: 3

## Naming

- Use camelCase for variables. Confidence: 0.90
  - Signal: 8 reinforcing, 0 contradicting
  - Sessions seen: 4

## Learning (not yet active)

- [Imports] Prefer named imports over default. Confidence: 0.50
  - Signal: 1 reinforcing, 0 contradicting
  - Sessions seen: 1
`;

function seed(content: string): void {
  fs.writeFileSync(storagePaths.habitsFile, content);
}

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-habits-sync-'));
  storagePaths.habitsFile = path.join(tmpDir, 'habits.md');
  seed(SEEDED);
});

afterEach(() => {
  Object.assign(storagePaths, origStorage);
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

describe('renderPortableBody', () => {
  it('includes active habits, sorted by category, excludes the learning section', () => {
    const body = renderPortableBody(parseHabits(SEEDED));
    expect(body).toContain('## Naming');
    expect(body).toContain('## TypeScript');
    expect(body).toContain('- Use camelCase for variables.');
    // sorted: Naming before TypeScript
    expect(body.indexOf('## Naming')).toBeLessThan(body.indexOf('## TypeScript'));
    // learning-section rule must NOT leak
    expect(body).not.toContain('Prefer named imports');
    // no confidence math / signal counts in the portable form
    expect(body).not.toContain('Confidence:');
    expect(body).not.toContain('Sessions seen');
  });

  it('respects the minConfidence filter', () => {
    const body = renderPortableBody(parseHabits(SEEDED), 0.85);
    expect(body).toContain('Use camelCase'); // 0.90 passes
    expect(body).not.toContain('explicit return types'); // 0.80 filtered out
  });
});

describe('renderBlockOrNull', () => {
  it('returns a body when active habits exist', () => {
    expect(renderBlockOrNull()).toContain('# Coding preferences');
  });

  it('returns null when there are no active habits', () => {
    seed(`<!-- cc-habits format v0.2 -->
# Coding habits

## Learning (not yet active)

- [Imports] Prefer named imports. Confidence: 0.50
  - Sessions seen: 1
`);
    expect(renderBlockOrNull()).toBeNull();
  });
});

describe('mergeBlock', () => {
  it('appends a block when none exists, preserving existing content', () => {
    const out = mergeBlock('# My Project\n\nNotes.\n', 'BODY');
    expect(out).toContain('# My Project');
    expect(out).toContain('Notes.');
    expect(out).toContain(BEGIN_MARKER);
    expect(out).toContain('BODY');
    expect(out).toContain(END_MARKER);
  });

  it('replaces an existing block idempotently (single marker pair)', () => {
    const first = mergeBlock('# Doc\n', 'BODY-1');
    const second = mergeBlock(first, 'BODY-2');
    expect((second.match(new RegExp(BEGIN_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) ?? []).length).toBe(1);
    expect(second).toContain('BODY-2');
    expect(second).not.toContain('BODY-1');
    expect(second).toContain('# Doc');
  });

  it('handles empty input', () => {
    const out = mergeBlock('', 'BODY');
    expect(out).toContain(BEGIN_MARKER);
    expect(out).toContain('BODY');
  });
});

describe('syncTargets', () => {
  it('writes AGENTS.md and merges with existing content', () => {
    const proj = path.join(tmpDir, 'proj');
    fs.mkdirSync(proj, { recursive: true });
    fs.writeFileSync(path.join(proj, 'AGENTS.md'), '# Project\n\nKeep me.\n');

    const result = syncTargets(['agents'], { baseDir: proj });
    expect(result.skipped).toBe(false);
    const content = fs.readFileSync(path.join(proj, 'AGENTS.md'), 'utf-8');
    expect(content).toContain('Keep me.');
    expect(content).toContain('# Coding preferences');
    expect(content).toContain('Use camelCase');
  });

  it('writes a Cursor .mdc with alwaysApply frontmatter', () => {
    const proj = path.join(tmpDir, 'proj-cursor');
    fs.mkdirSync(proj, { recursive: true });
    syncTargets(['cursor'], { baseDir: proj });
    const mdc = fs.readFileSync(path.join(proj, '.cursor', 'rules', 'cc-habits.mdc'), 'utf-8');
    expect(mdc).toMatch(/^---\n/);
    expect(mdc).toContain('alwaysApply: true');
    expect(mdc).toContain('Use camelCase');
  });

  it('writes .clinerules as a file when no directory exists', () => {
    const proj = path.join(tmpDir, 'proj-cline');
    fs.mkdirSync(proj, { recursive: true });
    syncTargets(['cline'], { baseDir: proj });
    expect(fs.existsSync(path.join(proj, '.clinerules'))).toBe(true);
    expect(fs.statSync(path.join(proj, '.clinerules')).isFile()).toBe(true);
  });

  it('writes inside .clinerules/ when it is a directory', () => {
    const proj = path.join(tmpDir, 'proj-clinedir');
    fs.mkdirSync(path.join(proj, '.clinerules'), { recursive: true });
    syncTargets(['cline'], { baseDir: proj });
    expect(fs.existsSync(path.join(proj, '.clinerules', 'cc-habits.md'))).toBe(true);
  });

  it('skips writing when there are no active habits', () => {
    seed(`<!-- cc-habits format v0.2 -->\n# Coding habits\n`);
    const proj = path.join(tmpDir, 'proj-empty');
    fs.mkdirSync(proj, { recursive: true });
    const result = syncTargets(['agents'], { baseDir: proj });
    expect(result.skipped).toBe(true);
    expect(result.written).toHaveLength(0);
    expect(fs.existsSync(path.join(proj, 'AGENTS.md'))).toBe(false);
  });

  it('refuses to write through a symlink', () => {
    const proj = path.join(tmpDir, 'proj-symlink');
    fs.mkdirSync(proj, { recursive: true });
    const target = path.join(tmpDir, 'real-target.md');
    fs.writeFileSync(target, 'secret');
    fs.symlinkSync(target, path.join(proj, 'AGENTS.md'));
    expect(() => syncTargets(['agents'], { baseDir: proj })).toThrow(/symlink/);
  });
});
