import { describe, it, expect } from 'vitest';
import { parseHabitsFile, parseMemoriesFile, parsePendingFile } from './parsers';

const HABITS_MD = `<!-- cc-habits format v0.2 -->
# Coding habits

## TypeScript

- Use explicit return types on exported functions. Confidence: 0.80
  - Sessions seen: 3

- Prefer const over let where possible. Confidence: 0.60
  - Sessions seen: 2

## Python

- Use f-strings instead of .format(). Confidence: 0.65
  - Sessions seen: 2

## Learning (not yet active)

- [Python] Use type hints on function signatures. Confidence: 0.50
  - Sessions seen: 1
`;

const MEMORIES_MD = `<!-- cc-habits memories format v0.1 -->
# Coding memories

Auto-generated by cc-habits. You may edit this file; memories you delete will not be recreated.

## Repeated mistakes

- When editing settings.json, do not overwrite existing hook arrays.
  - Trigger: settings.json, hooks, install
  - Correction: Merge new hooks with existing hooks
  - Confidence: 0.80
  - Seen: 3
  - Sessions seen: 2

## Candidates (not yet active)

> These memories have not been observed enough times or approved by the user. Agents should not apply memories in this section.

- [Repeated mistakes] When updating parser fields, also update format spec and tests.
  - Trigger: parser, storage
  - Correction: Keep parser and spec in lockstep
  - Confidence: 0.50
  - Seen: 1
  - Sessions seen: 1
`;

describe('parseHabitsFile', () => {
  it('returns categories from habits.md', () => {
    const cats = parseHabitsFile(HABITS_MD);
    expect(cats.has('TypeScript')).toBe(true);
    expect(cats.has('Python')).toBe(true);
    expect(cats.has('Learning')).toBe(true);
  });

  it('parses rule text and confidence correctly', () => {
    const cats = parseHabitsFile(HABITS_MD);
    const ts = cats.get('TypeScript') ?? [];
    expect(ts).toHaveLength(2);
    expect(ts[0].rule).toBe('Use explicit return types on exported functions');
    expect(ts[0].confidence).toBeCloseTo(0.80);
    expect(ts[0].isLearning).toBe(false);
  });

  it('marks learning section items as isLearning=true', () => {
    const cats = parseHabitsFile(HABITS_MD);
    const learning = cats.get('Learning') ?? [];
    expect(learning).toHaveLength(1);
    expect(learning[0].isLearning).toBe(true);
  });

  it('returns empty map for empty input', () => {
    expect(parseHabitsFile('').size).toBe(0);
    expect(parseHabitsFile('# Coding habits\n').size).toBe(0);
  });
});

describe('parseMemoriesFile', () => {
  it('parses active memory sections', () => {
    const sections = parseMemoriesFile(MEMORIES_MD);
    expect(sections.has('Repeated mistakes')).toBe(true);
  });

  it('parses active memory text, trigger, correction, and confidence', () => {
    const sections = parseMemoriesFile(MEMORIES_MD);
    const rm = sections.get('Repeated mistakes') ?? [];
    expect(rm.length).toBeGreaterThanOrEqual(1);
    const active = rm.find(m => !m.isCandidate);
    expect(active?.text).toContain('overwrite existing hook arrays');
    expect(active?.trigger).toContain('settings.json');
    expect(active?.correction).toContain('Merge new hooks');
    expect(active?.confidence).toBeCloseTo(0.80);
    expect(active?.isCandidate).toBe(false);
  });

  it('parses candidate memories as isCandidate=true', () => {
    const sections = parseMemoriesFile(MEMORIES_MD);
    const rm = sections.get('Repeated mistakes') ?? [];
    const candidate = rm.find(m => m.isCandidate);
    expect(candidate).toBeTruthy();
    expect(candidate?.isCandidate).toBe(true);
    expect(candidate?.text).toContain('updating parser fields');
  });

  it('returns empty map for empty or header-only input', () => {
    expect(parseMemoriesFile('').size).toBe(0);
    expect(parseMemoriesFile('<!-- cc-habits memories format v0.1 -->\n# Coding memories\n').size).toBe(0);
  });
});

describe('parsePendingFile', () => {
  it('parses a valid pending JSON array', () => {
    const items = parsePendingFile(JSON.stringify([
      { rule: 'Use f-strings', category: 'Python', reasoning: 'seen 3x' },
      { rule: 'Add type hints', category: 'TypeScript', reasoning: '' },
    ]));
    expect(items).toHaveLength(2);
    expect(items[0].rule).toBe('Use f-strings');
    expect(items[0].category).toBe('Python');
    expect(items[1].rule).toBe('Add type hints');
  });

  it('filters out items with empty rule', () => {
    const items = parsePendingFile(JSON.stringify([
      { rule: '', category: 'Python' },
      { rule: 'Valid rule', category: 'TypeScript' },
    ]));
    expect(items).toHaveLength(1);
    expect(items[0].rule).toBe('Valid rule');
  });

  it('returns empty array for malformed JSON', () => {
    expect(parsePendingFile('not json')).toEqual([]);
    expect(parsePendingFile('')).toEqual([]);
  });

  it('returns empty array for non-array JSON', () => {
    expect(parsePendingFile('{}')).toEqual([]);
  });
});
