import fs from 'fs';
import os from 'os';
import path from 'path';

// Maximum size of append-only log files before reads warn and skip. Prevents
// memory exhaustion if a runaway session generates huge payloads.
const MAX_LOG_READ_BYTES = 50 * 1024 * 1024; // 50 MB

export const FORMAT_VERSION = 'v0.2';

export interface Signal {
  ts: string;
  session_id: string;
  type: string;
  file: string;
  diff: string;
  language?: string;
}

export interface Habit {
  rule: string;
  confidence: number;
  reinforcing: number;
  contradicting: number;
  sessions_seen: number;
  last_session_id?: string;
  languages?: string[];
  first_learned?: string;
  last_updated?: string;
}

export type HabitsMap = Record<string, Habit[]>;

// C2: CC_HABITS_DIR overrides the default ~/.claude/habits location. This is
// the single source of truth — every other path is derived from it.
function defaultRoot(): string {
  return process.env['CC_HABITS_DIR'] ?? path.join(os.homedir(), '.claude', 'habits');
}

export const storagePaths = {
  habitsDir: defaultRoot(),
  habitsFile: path.join(defaultRoot(), 'habits.md'),
  logFile: path.join(defaultRoot(), 'log.jsonl'),
  errorLog: path.join(defaultRoot(), 'error.log'),
  tombstonesFile: path.join(defaultRoot(), '.tombstones.json'),
  snapshotFile: path.join(defaultRoot(), '.snapshot.json'),
  pendingFile: path.join(defaultRoot(), '.pending.json'),
  historyFile: path.join(defaultRoot(), '.history.jsonl'),
  provenanceFile: path.join(defaultRoot(), '.provenance.json'),
  // config.yml lives in the same directory as habits.md so that CC_HABITS_DIR
  // overrides both the data files AND the provider config in one env var.
  configFile: path.join(defaultRoot(), 'config.yml'),
};

const FILE_MODE = 0o600;

const HABITS_HEADER =
  `<!-- cc-habits format ${FORMAT_VERSION} -->\n` +
  '# Coding habits\n\n' +
  'Auto-generated by cc-habits. You may edit this file; rules you delete will not be recreated.\n';

const LEARNING_SECTION_HEADER =
  '\n## Learning (not yet active)\n\n' +
  '> These habits have been observed in only one session. They are quarantined ' +
  'here until reinforced in a second distinct session. Claude should not apply ' +
  'rules in this section.\n';

export function ensureDirs(): void {
  fs.mkdirSync(storagePaths.habitsDir, { recursive: true });
}

function safeWrite(filePath: string, content: string): void {
  // Symlink guard: refuse to write if the target is already a symlink.  An attacker
  // who pre-creates ~/.claude/habits/habits.md → /etc/passwd before cc-habits runs
  // would otherwise cause us to overwrite arbitrary files.
  if (fs.existsSync(filePath)) {
    if (fs.lstatSync(filePath).isSymbolicLink()) {
      throw new Error(`refusing to write through symlink: ${filePath}`);
    }
  }
  // Atomic write: write to a hidden temp file in the SAME directory, then rename.
  // This guarantees (a) no partial write is visible to concurrent readers, and
  // (b) even if a symlink is created between our lstat and the rename, renameSync
  // replaces the directory entry itself — it does NOT follow symlinks on the target.
  const dir = path.dirname(filePath);
  const tmpPath = path.join(dir, `.cc-habits-tmp-${process.pid}-${Date.now()}`);
  try {
    fs.writeFileSync(tmpPath, content, { encoding: 'utf-8', mode: FILE_MODE });
    fs.renameSync(tmpPath, filePath);
  } catch (e) {
    try { fs.unlinkSync(tmpPath); } catch { /* best-effort cleanup */ }
    throw e;
  }
}

function safeAppend(filePath: string, content: string): void {
  if (fs.existsSync(filePath)) {
    const stat = fs.lstatSync(filePath);
    if (stat.isSymbolicLink()) {
      throw new Error(`refusing to append through symlink: ${filePath}`);
    }
  }
  fs.appendFileSync(filePath, content, { encoding: 'utf-8', mode: FILE_MODE });
}

export function initHabitsMd(): void {
  ensureDirs();
  if (!fs.existsSync(storagePaths.habitsFile)) {
    safeWrite(storagePaths.habitsFile, HABITS_HEADER);
  }
}

export function initLog(): void {
  ensureDirs();
  if (!fs.existsSync(storagePaths.logFile)) {
    safeWrite(storagePaths.logFile, '');
  }
}

export function appendSignal(signal: Signal): void {
  ensureDirs();
  safeAppend(storagePaths.logFile, JSON.stringify(signal) + '\n');
}

export function readSignals(sessionId?: string): Signal[] {
  if (!fs.existsSync(storagePaths.logFile)) return [];
  // Guard against reading a runaway log file that could exhaust process memory.
  const stat = fs.statSync(storagePaths.logFile);
  if (stat.size > MAX_LOG_READ_BYTES) {
    // Log the oversized-file event and return empty rather than crash.
    logError(`readSignals: log.jsonl exceeds ${MAX_LOG_READ_BYTES} bytes; skipping read`);
    return [];
  }
  const lines = fs.readFileSync(storagePaths.logFile, 'utf-8').split('\n');
  const signals: Signal[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      const sig = JSON.parse(trimmed) as Signal;
      if (!sessionId || sig.session_id === sessionId) signals.push(sig);
    } catch {
      // skip malformed line
    }
  }
  return signals;
}

export function readHabitsMd(): string {
  if (!fs.existsSync(storagePaths.habitsFile)) return HABITS_HEADER;
  return fs.readFileSync(storagePaths.habitsFile, 'utf-8');
}

export function writeHabitsMd(content: string): void {
  ensureDirs();
  safeWrite(storagePaths.habitsFile, content);
}

// Tombstones (A2) ──────────────────────────────────────────────────────────
function normalizeRule(s: string): string {
  return s.trim().replace(/\.$/, '').toLowerCase();
}

export function readTombstones(): string[] {
  if (!fs.existsSync(storagePaths.tombstonesFile)) return [];
  try {
    const data = JSON.parse(fs.readFileSync(storagePaths.tombstonesFile, 'utf-8')) as unknown;
    if (Array.isArray(data)) return data.filter((x): x is string => typeof x === 'string');
  } catch {
    // malformed — treat as empty
  }
  return [];
}

export function writeTombstones(rules: string[]): void {
  ensureDirs();
  const unique = Array.from(new Set(rules.map(normalizeRule))).filter(Boolean);
  safeWrite(storagePaths.tombstonesFile, JSON.stringify(unique, null, 2) + '\n');
}

export function addTombstone(rule: string): void {
  const current = readTombstones();
  current.push(normalizeRule(rule));
  writeTombstones(current);
}

export function isTombstoned(rule: string): boolean {
  const target = normalizeRule(rule);
  return readTombstones().some(t => t === target);
}

// Snapshot (auto-detect manual deletes) ────────────────────────────────────
export function readSnapshot(): HabitsMap | null {
  if (!fs.existsSync(storagePaths.snapshotFile)) return null;
  try {
    return JSON.parse(fs.readFileSync(storagePaths.snapshotFile, 'utf-8')) as HabitsMap;
  } catch {
    return null;
  }
}

export function writeSnapshot(cats: HabitsMap): void {
  ensureDirs();
  safeWrite(storagePaths.snapshotFile, JSON.stringify(cats, null, 2));
}

// Compare snapshot to current parsed habits.md. Any rule present in snapshot
// but absent from current was manually deleted by the user — tombstone it.
export function detectManualDeletes(current: HabitsMap): string[] {
  const snapshot = readSnapshot();
  if (snapshot === null) return [];
  const currentRules = new Set<string>();
  for (const habits of Object.values(current)) {
    for (const h of habits) currentRules.add(normalizeRule(h.rule));
  }
  const deleted: string[] = [];
  for (const habits of Object.values(snapshot)) {
    for (const h of habits) {
      const norm = normalizeRule(h.rule);
      if (!currentRules.has(norm)) deleted.push(norm);
    }
  }
  return deleted;
}

// Pending updates staging (A4) ─────────────────────────────────────────────
export interface PendingUpdate {
  category: string;
  rule: string;
  decision: string;
  matched_habit_id?: string;
  reasoning?: string;
  ts: string;
}

export function readPending(): PendingUpdate[] {
  if (!fs.existsSync(storagePaths.pendingFile)) return [];
  try {
    const data = JSON.parse(fs.readFileSync(storagePaths.pendingFile, 'utf-8')) as unknown;
    if (Array.isArray(data)) return data as PendingUpdate[];
  } catch {
    // ignore
  }
  return [];
}

export function writePending(updates: PendingUpdate[]): void {
  ensureDirs();
  safeWrite(storagePaths.pendingFile, JSON.stringify(updates, null, 2));
}

export function clearPending(): void {
  if (fs.existsSync(storagePaths.pendingFile)) {
    fs.unlinkSync(storagePaths.pendingFile);
  }
}

// History (B1: diff) ───────────────────────────────────────────────────────
export interface HistoryEntry {
  ts: string;
  session_id?: string;
  habits_md: string;
}

export function appendHistory(entry: HistoryEntry): void {
  ensureDirs();
  safeAppend(storagePaths.historyFile, JSON.stringify(entry) + '\n');
}

export function readHistory(): HistoryEntry[] {
  if (!fs.existsSync(storagePaths.historyFile)) return [];
  const stat = fs.statSync(storagePaths.historyFile);
  if (stat.size > MAX_LOG_READ_BYTES) {
    logError(`readHistory: .history.jsonl exceeds ${MAX_LOG_READ_BYTES} bytes; skipping read`);
    return [];
  }
  const lines = fs.readFileSync(storagePaths.historyFile, 'utf-8').split('\n');
  const out: HistoryEntry[] = [];
  for (const line of lines) {
    const t = line.trim();
    if (!t) continue;
    try { out.push(JSON.parse(t) as HistoryEntry); } catch { /* skip */ }
  }
  return out;
}

// Provenance (B2: explain) ─────────────────────────────────────────────────
export interface ProvenanceRef {
  ts: string;
  session_id: string;
  file: string;
  snippet: string;
  decision: string;
}

export type ProvenanceMap = Record<string, ProvenanceRef[]>;

export function readProvenance(): ProvenanceMap {
  if (!fs.existsSync(storagePaths.provenanceFile)) return {};
  try {
    return JSON.parse(fs.readFileSync(storagePaths.provenanceFile, 'utf-8')) as ProvenanceMap;
  } catch {
    return {};
  }
}

export function writeProvenance(m: ProvenanceMap): void {
  ensureDirs();
  safeWrite(storagePaths.provenanceFile, JSON.stringify(m, null, 2));
}

export function appendProvenance(ruleKey: string, refs: ProvenanceRef[]): void {
  const map = readProvenance();
  const key = ruleKey.trim().replace(/\.$/, '').toLowerCase();
  const existing = map[key] ?? [];
  // Cap per-rule provenance at 10 most-recent entries to bound disk usage.
  const merged = [...existing, ...refs].slice(-10);
  map[key] = merged;
  writeProvenance(map);
}

export function lookupProvenance(rule: string): ProvenanceRef[] {
  const key = rule.trim().replace(/\.$/, '').toLowerCase();
  const map = readProvenance();
  if (map[key]) return map[key];
  // Fuzzy: substring match.
  for (const k of Object.keys(map)) {
    if (k.includes(key) || key.includes(k)) return map[k];
  }
  return [];
}

// Habits parsing / serialising ─────────────────────────────────────────────
export function parseHabits(md: string): HabitsMap {
  const cats: HabitsMap = {};
  let currentCat: string | null = null;
  let currentHabit: Habit | null = null;
  let inLearning = false;

  const flush = (): void => {
    if (currentHabit !== null && currentCat !== null) {
      if (!cats[currentCat]) cats[currentCat] = [];
      cats[currentCat].push(currentHabit);
      currentHabit = null;
    }
  };

  for (const line of md.split('\n')) {
    if (line.startsWith('## Learning')) {
      flush();
      inLearning = true;
      currentCat = null;
      continue;
    }
    if (line.startsWith('## ')) {
      flush();
      currentCat = line.slice(3).trim();
      inLearning = false;
      if (!cats[currentCat]) cats[currentCat] = [];
    } else if (line.startsWith('- ')) {
      // In the learning section, lines are prefixed with [Category]
      let bodyLine = line;
      let learnCat: string | null = null;
      if (inLearning) {
        const m = line.match(/^- \[([^\]]+)\]\s+(.+)$/);
        if (!m) continue;
        learnCat = m[1].trim();
        bodyLine = `- ${m[2]}`;
      }
      const m = bodyLine.match(/^- (.+?)\.\s+Confidence:\s+([\d.]+)/);
      if (m) {
        flush();
        const cat: string | null = inLearning ? learnCat : currentCat;
        if (cat === null) continue;
        if (!cats[cat]) cats[cat] = [];
        currentHabit = {
          rule: m[1].trim(),
          confidence: parseFloat(m[2]),
          reinforcing: 0,
          contradicting: 0,
          sessions_seen: 1,
        };
        // Adopt this category for flushing
        currentCat = cat;
      }
    } else if (line.trim().startsWith('- Signal:') && currentHabit !== null) {
      const m = line.match(/- Signal:\s*(\d+)\s+reinforcing,\s*(\d+)\s+contradicting/);
      if (m) {
        currentHabit.reinforcing = parseInt(m[1], 10);
        currentHabit.contradicting = parseInt(m[2], 10);
      }
    } else if (line.trim().startsWith('- Sessions seen:') && currentHabit !== null) {
      const m = line.match(/- Sessions seen:\s*(\d+)/);
      if (m) currentHabit.sessions_seen = parseInt(m[1], 10);
    } else if (line.trim().startsWith('- Languages:') && currentHabit !== null) {
      const m = line.match(/- Languages:\s*(.+)/);
      if (m) currentHabit.languages = m[1].split(',').map(s => s.trim()).filter(Boolean);
    } else if (line.trim().startsWith('- First learned:') && currentHabit !== null) {
      currentHabit.first_learned = line.split(':').slice(1).join(':').trim();
    } else if (line.trim().startsWith('- Last updated:') && currentHabit !== null) {
      currentHabit.last_updated = line.split(':').slice(1).join(':').trim();
    }
  }

  flush();
  return cats;
}

function renderHabit(h: Habit, lines: string[], categoryPrefix?: string): void {
  const rule = h.rule.trim().replace(/\.$/, '');
  const prefix = categoryPrefix ? `[${categoryPrefix}] ` : '';
  lines.push(`- ${prefix}${rule}. Confidence: ${h.confidence.toFixed(2)}`);
  lines.push(`  - Signal: ${h.reinforcing} reinforcing, ${h.contradicting} contradicting`);
  lines.push(`  - Sessions seen: ${h.sessions_seen}`);
  if (h.languages && h.languages.length > 0) {
    lines.push(`  - Languages: ${h.languages.join(', ')}`);
  }
  if (h.first_learned) lines.push(`  - First learned: ${h.first_learned}`);
  if (h.last_updated) lines.push(`  - Last updated: ${h.last_updated}`);
  lines.push('');
}

export function serialiseHabits(cats: HabitsMap): string {
  const lines: string[] = [
    `<!-- cc-habits format ${FORMAT_VERSION} -->`,
    '# Coding habits',
    '',
    'Auto-generated by cc-habits. You may edit this file; rules you delete will not be recreated.',
  ];

  const active: HabitsMap = {};
  const learning: Array<[string, Habit]> = [];

  for (const category of Object.keys(cats)) {
    for (const h of cats[category] ?? []) {
      if ((h.sessions_seen ?? 1) >= 2) {
        if (!active[category]) active[category] = [];
        active[category].push(h);
      } else {
        learning.push([category, h]);
      }
    }
  }

  for (const category of Object.keys(active).sort()) {
    const habits = active[category];
    if (!habits || habits.length === 0) continue;
    lines.push('', `## ${category}`, '');
    for (const h of habits) renderHabit(h, lines);
  }

  if (learning.length > 0) {
    lines.push(LEARNING_SECTION_HEADER);
    for (const [category, h] of learning) renderHabit(h, lines, category);
  }

  return lines.join('\n');
}

export function logError(msg: string): void {
  try {
    ensureDirs();
    const entry = `[${new Date().toISOString()}] ${msg}\n`;
    safeAppend(storagePaths.errorLog, entry);
  } catch {
    // never crash
  }
}

// Path sanitization (S4) ───────────────────────────────────────────────────
export function sanitizeFilePath(p: string): string {
  // Strip any traversal segments; collapse to a safe representation.
  // We keep the path for human-readability but drop dangerous fragments.
  if (!p) return '';
  // Reject literal control characters that could break log line parsing.
  const cleaned = p.replace(/[\x00-\x1f]/g, '');
  // Block path traversal: replace `..` segments with `_` so the displayed
  // path is unambiguous and cannot be re-interpreted by other tools.
  return cleaned.split('/').map(seg => seg === '..' ? '_' : seg).join('/');
}
