import fs from 'fs';
import path from 'path';
import { readHabitsMd, parseHabits, HabitsMap, Habit, storagePaths } from './storage';
import { sanitizeRule } from './confidence';

// cc-habits sync — emit Claude-learned habits into portable preference files that
// other coding agents (Cursor, Cline, Codex, Amp, …) can read. Learning happens
// via Claude Code hooks; sync is the one-way bridge that carries those habits out
// to every other tool in the developer's workflow.

export const BEGIN_MARKER = '<!-- BEGIN cc-habits (auto-generated; edit habits via `cc-habits`) -->';
export const END_MARKER = '<!-- END cc-habits -->';

export type SyncTarget = 'agents' | 'cursor' | 'copilot' | 'gemini' | 'cline' | 'aider' | 'continue' | 'jetbrains' | 'windsurf';

const DEFAULT_MIN_CONFIDENCE = 0.3;


// Only active, sufficiently-confident habits leave the cc-habits store. Learning-section
// (single-session) habits are never exported — they are not yet trusted.
function activeHabits(cats: HabitsMap, minConfidence: number): HabitsMap {
  const active: HabitsMap = {};
  for (const category of Object.keys(cats)) {
    for (const h of cats[category] ?? []) {
      if ((h.sessions_seen ?? 1) >= 2 && h.confidence >= minConfidence) {
        if (!active[category]) active[category] = [];
        active[category].push(h);
      }
    }
  }
  return active;
}

function ruleLine(h: Habit): string {
  // SEC: sanitize at export time — synced files are read by other agents (Cursor,
  // Cline, AGENTS.md) whose injection-resistance may be weaker than Claude Code's.
  const safe = sanitizeRule(h.rule.trim().replace(/\.$/, ''));
  return safe ? `- ${safe}.` : '';
}

// The portable body shared by every target: a clean, instruction-style markdown
// section with no confidence math or signal counts — those are cc-habits internals
// that would only add noise to an agent's context.
export function renderPortableBody(cats: HabitsMap, minConfidence = DEFAULT_MIN_CONFIDENCE): string {
  const active = activeHabits(cats, minConfidence);
  const categories = Object.keys(active).sort();
  const lines: string[] = [
    '# Coding preferences',
    '',
    '> Generated by cc-habits from observed coding patterns. These rules are inferences,',
    '> not declarations — review before sharing. Best-effort redaction applied; rule text',
    '> may reflect patterns from proprietary code.',
    '',
    'Follow these preferences when generating or editing code in this repository.',
  ];
  for (const category of categories) {
    const habits = active[category];
    if (!habits || habits.length === 0) continue;
    lines.push('', `## ${category}`, '');
    for (const h of habits) {
      const line = ruleLine(h);
      if (line) lines.push(line);
    }
  }
  return lines.join('\n');
}

// Returns null when there is nothing worth emitting (no active habits). Callers
// should skip writing in that case rather than emit an empty block.
export function renderBlockOrNull(minConfidence = DEFAULT_MIN_CONFIDENCE): string | null {
  const cats = parseHabits(readHabitsMd());
  const active = activeHabits(cats, minConfidence);
  if (Object.keys(active).length === 0) return null;
  return renderPortableBody(cats, minConfidence);
}

// Insert or replace the cc-habits block in existing content. Everything outside the
// markers is preserved verbatim, so a hand-written AGENTS.md keeps its own content.
export function mergeBlock(existing: string, body: string): string {
  const block = `${BEGIN_MARKER}\n${body}\n${END_MARKER}`;
  const begin = existing.indexOf(BEGIN_MARKER);
  const end = existing.indexOf(END_MARKER);
  if (begin !== -1 && end !== -1 && end > begin) {
    const before = existing.slice(0, begin);
    const after = existing.slice(end + END_MARKER.length);
    return `${before.trimEnd()}\n\n${block}\n${after.trimStart() ? '\n' + after.trimStart() : ''}`.trimEnd() + '\n';
  }
  if (!existing.trim()) return block + '\n';
  return existing.trimEnd() + `\n\n${block}\n`;
}

// Cursor reads .cursor/rules/*.mdc files with YAML frontmatter. alwaysApply makes
// the rule unconditional, matching the "inject every conversation" intent.
function cursorMdc(body: string): string {
  return [
    '---',
    'description: Learned coding habits (cc-habits)',
    'alwaysApply: true',
    '---',
    '',
    body,
    '',
  ].join('\n');
}

function targetPath(target: SyncTarget, baseDir: string): string {
  switch (target) {
    case 'agents': return path.join(baseDir, 'AGENTS.md');
    case 'cursor': return path.join(baseDir, '.cursor', 'rules', 'cc-habits.mdc');
    case 'copilot': return path.join(baseDir, '.github', 'copilot-instructions.md');
    case 'gemini': return path.join(baseDir, 'GEMINI.md');
    case 'cline': {
      const dir = path.join(baseDir, '.clinerules');
      if (fs.existsSync(dir) && fs.lstatSync(dir).isDirectory()) {
        return path.join(dir, 'cc-habits.md');
      }
      return dir;
    }
    case 'aider': return path.join(baseDir, 'AIDER.md');
    case 'continue': return path.join(baseDir, '.continuerules');
    case 'jetbrains': return path.join(baseDir, '.aiassistant', 'rules', 'cc-habits.md');
    case 'windsurf': return path.join(baseDir, '.windsurfrules');
  }
}

function safeWriteProjectFile(filePath: string, content: string): void {
  if (fs.existsSync(filePath)) {
    const stat = fs.lstatSync(filePath);
    if (stat.isSymbolicLink()) {
      throw new Error(`refusing to write through symlink: ${filePath}`);
    }
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

export interface SyncResult {
  written: string[];
  skipped: boolean; // true when there were no active habits to emit
}

// Write habits into the chosen target files under baseDir (defaults to cwd).
// Cursor gets a dedicated .mdc file (overwritten); agents/cline merge a marked
// block so any existing user content is preserved.
export function syncTargets(
  targets: SyncTarget[],
  opts: { baseDir?: string; minConfidence?: number } = {},
): SyncResult {
  const baseDir = opts.baseDir ?? process.cwd();
  const minConfidence = opts.minConfidence ?? DEFAULT_MIN_CONFIDENCE;
  const body = renderBlockOrNull(minConfidence);
  if (body === null) return { written: [], skipped: true };

  const written: string[] = [];
  for (const target of targets) {
    const dest = targetPath(target, baseDir);
    if (target === 'cursor') {
      safeWriteProjectFile(dest, cursorMdc(body));
    } else {
      const existing = fs.existsSync(dest) && !fs.lstatSync(dest).isSymbolicLink()
        ? fs.readFileSync(dest, 'utf-8')
        : '';
      safeWriteProjectFile(dest, mergeBlock(existing, body));
    }
    written.push(dest);
  }
  return { written, skipped: false };
}

export function readSyncTargets(): SyncTarget[] {
  if (!fs.existsSync(storagePaths.configFile)) return [];
  try {
    const text = fs.readFileSync(storagePaths.configFile, 'utf-8');
    const m = text.match(/sync_targets\s*:\s*\[?([^\]\n#]+)\]?/);
    if (m) {
      const allowed = new Set(['agents', 'cursor', 'copilot', 'gemini', 'cline', 'aider', 'continue', 'jetbrains', 'windsurf']);
      return m[1]
        .split(',')
        .map(x => x.trim().replace(/['"]/g, '') as SyncTarget)
        .filter(t => allowed.has(t));
    }
  } catch {
    // ignore
  }
  return [];
}

